{"name": "test_fail2", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail2():\n>       assert False\nE       assert False\n\ntests\\test_fail.py:8: AssertionError"}, "start": 1697561832308, "stop": 1697561832308, "uuid": "888aae0f-9661-40c8-82fb-3307d1a5bdd0", "historyId": "b58b7e867ac7b16c913dc6636c3475a0", "testCaseId": "43dedf1ef931d11918e6b05b9130314b", "fullName": "tests.test_fail#test_fail2", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "DESKTOP-S15PP4S"}, {"name": "thread", "value": "6684-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_fail"}]}